modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"

[[mods]]
modId = "roughlyenoughitems"
version = "${version}"
displayName = "Roughly Enough Items (REI)"
description = '''
To allow players to view items and recipes.
'''

[[dependencies.roughlyenoughitems]]
modId = "architectury"
mandatory = true
versionRange = "[8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "cloth_config"
mandatory = true
versionRange = "[10.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "forge"
mandatory = true
versionRange = "[45.0.0,)"
ordering = "NONE"
side = "BOTH"
